name: Build Mod DLL

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Build with MSBuild
      run: dotnet build --configuration Release

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LongYinTalentTweaks-DLL
        path: "**/bin/Release/**/LongYinTalentTweaks.dll"
